/**
 * Cleans the Figma icon exports and generates the React icon layer.
 *
 * Figma exports a component symbol together with the chrome of the section it
 * sits in — a grey backing rect and the section's own rounded-rect border. The
 * real glyph is the `<g id="Icon/Name">` subtree. This lifts that subtree out
 * verbatim, so the committed geometry is Figma's, then rebinds the hard-coded
 * ink colour to `currentColor` so the icons inherit text colour.
 *
 * Run with `npm run build:icons` after re-downloading any export.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'

const ICON_DIR = path.join(process.cwd(), 'src/assets/icons')
const OUT_DIR = path.join(process.cwd(), 'src/components/icons')

/**
 * Ten of the twelve glyphs are single-colour strokes in ink/primary, which
 * becomes `currentColor` so they inherit text colour. `Verified` is a two-tone
 * badge — a brand star behind a white check — and stays explicitly coloured,
 * bound to the tokens rather than to raw hex.
 */
const COLOUR_MAP = [
  [/#191008/gi, 'currentColor'],
  [/#F25F2C/gi, 'var(--color-brand-primary)'],
  [/"white"/gi, '"var(--color-surface-default)"'],
]

const rebindColours = (svg) =>
  COLOUR_MAP.reduce((acc, [pattern, replacement]) => acc.replace(pattern, replacement), svg)

const pascal = (slug) =>
  slug
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')

function extractGlyph(svg, file) {
  const open = svg.search(/<g id="Icon\/[^"]*">/)

  // No wrapper means this file has already been cleaned by a previous run, so
  // the whole svg body is the glyph. Keeps the script idempotent.
  if (open === -1) {
    const inner = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/)
    if (!inner) throw new Error(`Neither an Icon/ group nor an <svg> body in ${file}`)
    return rebindColours(inner[1]).trim()
  }

  const bodyStart = svg.indexOf('>', open) + 1

  // Walk forward counting nesting so we close on the matching </g>.
  let depth = 1
  let i = bodyStart
  while (depth > 0) {
    const nextOpen = svg.indexOf('<g', i)
    const nextClose = svg.indexOf('</g>', i)
    if (nextClose === -1) throw new Error(`Unbalanced <g> in ${file}`)
    if (nextOpen !== -1 && nextOpen < nextClose) {
      depth += 1
      i = nextOpen + 2
    } else {
      depth -= 1
      i = nextClose + 4
    }
  }

  return rebindColours(svg.slice(bodyStart, i - 4))
    .replace(/\sid="[^"]*"/g, '')
    .trim()
}

const files = (await readdir(ICON_DIR)).filter((f) => f.endsWith('.svg')).sort()
const icons = []

for (const file of files) {
  const slug = file.replace(/\.svg$/, '')
  const raw = await readFile(path.join(ICON_DIR, file), 'utf8')
  const glyph = extractGlyph(raw, file)

  // Rewrite the asset itself so the committed file is the glyph alone.
  await writeFile(
    path.join(ICON_DIR, file),
    `<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">\n${glyph
      .split('\n')
      .map((l) => l.trim())
      .filter(Boolean)
      .map((l) => `  ${l}`)
      .join('\n')}\n</svg>\n`,
  )

  const name = `${pascal(slug)}Icon`
  const body = glyph
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((l) => `      ${l.replace(/\/>$/, ' />')}`)
    .join('\n')

  await writeFile(
    path.join(OUT_DIR, `${name}.tsx`),
    `import type { IconProps } from './types'

/** Figma \`Icon/${pascal(slug)}\`, geometry exported from node set 207:1595. */
export function ${name}({ size = 24, ...props }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
      focusable="false"
      {...props}
    >
${body}
    </svg>
  )
}
`,
  )

  icons.push({ slug, name })
}

await writeFile(
  path.join(OUT_DIR, 'index.ts'),
  `// Generated by scripts/build-icons.mjs — do not edit by hand.
export type { IconProps } from './types'

// The twelve first-party MyTicket glyphs.
${icons.map(({ name }) => `export { ${name} } from './${name}'`).join('\n')}

// Phosphor stand-ins for everything the custom set does not draw.
export * from './phosphor'

// The glyphs the page cards draw from Phosphor at a pinned weight.
export * from './card-glyphs'
`,
)

console.log(`Generated ${icons.length} icons: ${icons.map((i) => i.slug).join(', ')}`)
